Add Volumes To Remote Copy Groups for HTTP
farhan7500/hpe3par_python_sdk pull request #5
Opened 2018-08-29 12:56 UTC by nirupaman

2018-08-29 12:58 UTC, nirupaman commented
@farhan7500 Please review

2018-08-30 04:27 UTC, farhan7500 requested changes
Please check if we can cover more by generating the code coverage of the remote copy module.

2018-08-30 04:27 UTC, farhan7500 commented on test/HPE3ParMockServer_flask.py
> +          return resp
Please set resp value in if else and return resp only at the end

if 'query' in flask.request.args:
    ....
    ....
    
else:
   ....
   ....
return resp

2018-08-30 05:01 UTC, nirupaman commented on test/HPE3ParMockServer_flask.py
> +          return resp
have change the code to return resp at the end

2018-08-30 05:56 UTC, nirupaman commented
@farhan7500 If changes i made is correct or something more need to done in function

2018-08-30 06:50 UTC, farhan7500 requested changes

2018-08-30 06:50 UTC, farhan7500 commented on test/HPE3ParMockServer_flask.py
> +	resp = flask.make_response(json.dumps(vluns), 200)
Why are there 2 space separation in else? We need to be consistent. Is this really working?

2018-08-30 06:51 UTC, farhan7500 commented
Also, when I run the unit tests for coverage, there are indentation issue. Please fix all indentation issues so we can run the code coverage

Command: sudo tox -e cover test/test_HPE3ParClient_volume.py

 File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/nirun/hpe3par_python_sdk/test/test_HPE3ParClient_volume.py", line 724
    self.cl.FLASH_CACHE_ENABLED = 1
                                  ^
TabError: inconsistent use of tabs and spaces in indentation

2018-08-30 08:20 UTC, nirupaman commented
@farhan7500    tabs and spaces removed

2018-08-30 08:20 UTC, farhan7500 approved these changes

2018-08-30 08:21 UTC, merged