Schedule for client.py
farhan7500/hpe3par_python_sdk pull request #9
Opened 2018-09-26 05:25 UTC by nirupaman

@schedule

2018-09-27 09:32 UTC, nirupaman commented
@farhan7500 please review ..Whether i have to create test for sdk ?

2018-09-28 04:23 UTC, nirupaman commented
@please review

2018-09-28 04:23 UTC, nirupaman commented
@farhan7500

2018-09-28 04:50 UTC, farhan7500 commented on hpe3par_sdk/client.py
> +            self.getSchedule(name)
What are we checking here?

2018-10-01 03:25 UTC, nirupaman commented on hpe3par_sdk/client.py
> +            self.getSchedule(name)
have push the latest changes

2018-10-01 04:35 UTC, farhan7500 commented
Please remove all changes unrelated to your commit, only then can I review

2018-10-01 12:19 UTC, nirupaman commented
Run for create, get, schedule exist and delete schedule

root@cssosbe03-b12:/home/nirun/niru_ansiblecopy/hpe3par_python_sdk# vim test_snap.py
root@cssosbe03-b12:/home/nirun/niru_ansiblecopy/hpe3par_python_sdk# python test_snap.py
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

2018-10-03 04:38 UTC, farhan7500 requested changes

2018-10-03 04:38 UTC, farhan7500 commented on hpe3par_sdk/client.py
> +    def getRemoteCopyGroupVolume(self, remoteCopyGroupName, volumeName):
Why do we have remote copy changes in this PR?

2018-10-08 05:26 UTC, nirupaman commented
Repo deleted.

2018-10-08 05:26 UTC, closed without merging